# Generated by Django 5.2.3 on 2025-06-20 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccesoAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador')),
            ],
        ),
    ]
