# Generated by Django 5.1.6 on 2025-03-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('estado_cliente', models.CharField(default='Activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('token_recuperacion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administradores.administrador')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Radicacion',
            fields=[
                ('id_radicacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_radicado', models.CharField(max_length=50, unique=True)),
                ('fecha_radicado', models.DateField()),
                ('fecha_ultima_actuacion', models.DateField(blank=True, null=True)),
                ('despacho_departamento', models.CharField(blank=True, max_length=200, null=True)),
                ('sujetos_procesales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado_radicado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
                ('proceso_consultado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=3)),
                ('cliente', models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'db_table': 'radicaciones',
            },
        ),
    ]
