# Generated by Django 5.1.6 on 2025-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='Sin especificar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefono',
            field=models.CharField(default='Por actualizar', max_length=20),
            preserve_default=False,
        ),
    ]
