# Generated by Django 5.1.6 on 2025-03-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_ciudad_alter_cliente_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radicacion',
            name='numero_radicado',
            field=models.CharField(max_length=50),
        ),
    ]
